# Generated by Django 6.0.6 on 2026-06-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.CharField(default='4 Hours', max_length=50),
            preserve_default=False,
        ),
    ]
